services:
  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   restart: always
  #   environment:
  #     POSTGRES_USER: test
  #     POSTGRES_PASSWORD: changemeinprod!
  #     POSTGRES_DB: basicemail
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  back:
    build: ./
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
