#Use node js as base image
FROM node:lts-alpine

#Work directory to follow the instructions 
WORKDIR /front

#Copy files from package.json to /front directory
COPY package.json /front/

#Install package copied
RUN npm install

#Copy the project into front directory
COPY . /front/

#Expose the port 3000
EXPOSE 3000

#Execute the command to start the frontend
CMD ["npm", "start"]

