name: Node.js CI

on:
  push:
    branches: [ "send_userstorie" ]
  pull_request:
    branches: [ "send_userstorie" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.9, 3.10]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Python Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r backend/emailbackend/requirements.txt
    - name: Run Tests
      run: |
        python3 backend/emailbackend/manage.py test
  
    - name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: | 
        cd frontend
        npm ci
        npm run build --if-present
