version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "3000:80"
    environment:
      - STAGE=PROD
      - API_URL=http://example.com/api